/**
 * utils/sendEmail.js
 *
 * Sends the daily Excel report as an email attachment via Nodemailer.
 *
 * Required env vars:
 *   SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS
 *   REPORT_EMAIL_FROM, REPORT_EMAIL_TO
 */

const nodemailer = require('nodemailer');
const path = require('path');

/**
 * Build the HTML email body from a summary object.
 * @param {object} summary
 * @param {object[]} changes  Array of change objects (may be empty).
 * @returns {string} HTML
 */
function buildEmailBody(summary, changes = []) {
  const dateStr = summary.date || new Date().toLocaleDateString();

  const changeRows = changes.length
    ? changes
        .map(
          (c) =>
            `<tr>
               <td style="padding:4px 8px">${c.target}</td>
               <td style="padding:4px 8px">${c.type}</td>
               <td style="padding:4px 8px">${c.label || ''}</td>
               <td style="padding:4px 8px;color:${c.change === 'now_blacklisted' ? '#c00' : '#080'}">${c.change}</td>
             </tr>`
        )
        .join('')
    : '<tr><td colspan="4" style="padding:4px 8px;color:#888">No changes detected</td></tr>';

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/></head>
<body style="font-family:Arial,sans-serif;color:#333;max-width:700px;margin:auto">
  <h2 style="background:#1a1a2e;color:#fff;padding:16px;border-radius:4px">
    🛡 Daily Blacklist Monitoring Report – ${dateStr}
  </h2>

  <table style="width:100%;border-collapse:collapse;margin-bottom:24px">
    <tr style="background:#f0f0f0">
      <th style="padding:8px;text-align:left">Metric</th>
      <th style="padding:8px;text-align:right">Count</th>
    </tr>
    <tr>
      <td style="padding:8px">Total targets checked</td>
      <td style="padding:8px;text-align:right"><strong>${summary.total}</strong></td>
    </tr>
    <tr style="background:#f9f9f9">
      <td style="padding:8px">✅ Clean / Safe</td>
      <td style="padding:8px;text-align:right;color:#080"><strong>${summary.clean}</strong></td>
    </tr>
    <tr>
      <td style="padding:8px">⚠️ Suspicious</td>
      <td style="padding:8px;text-align:right;color:#b60"><strong>${summary.suspicious}</strong></td>
    </tr>
    <tr style="background:#f9f9f9">
      <td style="padding:8px">🚨 Blacklisted</td>
      <td style="padding:8px;text-align:right;color:#c00"><strong>${summary.blacklisted}</strong></td>
    </tr>
    <tr>
      <td style="padding:8px">❌ Errors</td>
      <td style="padding:8px;text-align:right"><strong>${summary.errors}</strong></td>
    </tr>
  </table>

  <h3>Changes Since Yesterday</h3>
  <table style="width:100%;border-collapse:collapse">
    <tr style="background:#f0f0f0">
      <th style="padding:4px 8px;text-align:left">Target</th>
      <th style="padding:4px 8px;text-align:left">Type</th>
      <th style="padding:4px 8px;text-align:left">Label</th>
      <th style="padding:4px 8px;text-align:left">Change</th>
    </tr>
    ${changeRows}
  </table>

  <p style="margin-top:24px;color:#888;font-size:12px">
    Full details are attached as an Excel file.<br/>
    Generated by Domain Blacklist Monitor.
  </p>
</body>
</html>`;
}

/**
 * Send the daily report email.
 *
 * @param {string} excelFilePath  Absolute path to the generated Excel file.
 * @param {object} summary        Summary counts object.
 * @param {object[]} changes      Array of change objects.
 * @returns {Promise<void>}
 */
async function sendReportEmail(excelFilePath, summary, changes = []) {
  const {
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    REPORT_EMAIL_FROM,
    REPORT_EMAIL_TO,
  } = process.env;

  if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS || !REPORT_EMAIL_TO) {
    console.warn('[sendEmail] SMTP settings incomplete – email skipped.');
    return;
  }

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT || '587', 10),
    secure: parseInt(SMTP_PORT || '587', 10) === 465,
    auth: { user: SMTP_USER, pass: SMTP_PASS },
  });

  const dateStr = summary.date || new Date().toISOString().split('T')[0];
  const subject = `Daily Blacklist Monitoring Report – ${dateStr}`;
  const html = buildEmailBody(summary, changes);

  const mailOptions = {
    from: REPORT_EMAIL_FROM || SMTP_USER,
    to: REPORT_EMAIL_TO,
    subject,
    html,
    attachments: [
      {
        filename: path.basename(excelFilePath),
        path: excelFilePath,
        contentType:
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      },
    ],
  };

  await transporter.sendMail(mailOptions);
  console.log(`[sendEmail] Report sent to ${REPORT_EMAIL_TO}`);
}

module.exports = { sendReportEmail, buildEmailBody };
